// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG3WIMNvQdJe9Nuoy4lQlCfjQQbpUjlrM',
    appId: '1:59221338803:web:22d62d834327e1a2f9dec6',
    messagingSenderId: '59221338803',
    projectId: 'power-motoring-app',
    authDomain: 'power-motoring-app.firebaseapp.com',
    storageBucket: 'power-motoring-app.appspot.com',
    measurementId: 'G-31SHN4SKB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6K5pya5wH2kvkevT_EmvSxQ8hmcxqd4M',
    appId: '1:59221338803:android:f8512ee4b2e93e9cf9dec6',
    messagingSenderId: '59221338803',
    projectId: 'power-motoring-app',
    storageBucket: 'power-motoring-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF3lycRpYjt_qcpEbFxGeprchQgoDdJmc',
    appId: '1:59221338803:ios:d7be6f853418720af9dec6',
    messagingSenderId: '59221338803',
    projectId: 'power-motoring-app',
    storageBucket: 'power-motoring-app.appspot.com',
    androidClientId: '59221338803-3t64464b6g6qacsbq4lpn20bq5lrbjsj.apps.googleusercontent.com',
    iosClientId: '59221338803-kdtrs548956cdfku6qkf814ut2ue5594.apps.googleusercontent.com',
    iosBundleId: 'com.powerMotoring.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF3lycRpYjt_qcpEbFxGeprchQgoDdJmc',
    appId: '1:59221338803:ios:a7f7a3c0d8db463bf9dec6',
    messagingSenderId: '59221338803',
    projectId: 'power-motoring-app',
    storageBucket: 'power-motoring-app.appspot.com',
    androidClientId: '59221338803-3t64464b6g6qacsbq4lpn20bq5lrbjsj.apps.googleusercontent.com',
    iosClientId: '59221338803-201qqulio6vli8stc3rjq7gea8r76eag.apps.googleusercontent.com',
    iosBundleId: 'com.powerMotoring.app.RunnerTests',
  );
}
