name: power_motoring
description: "Power Motoring project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1
  lottie: ^3.0.0
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0
  marquee: ^2.2.3
  socket_io_client: ^2.0.1
  google_sign_in: ^6.2.1
  app_settings: ^5.1.1
  pretty_gauge: ^1.0.1
  razorpay_flutter: ^1.3.6
  url_launcher: ^6.2.4
  flutter_typeahead: ^5.2.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_in_app_messaging: ^0.7.4+13
  firebase_analytics: ^10.8.5
  firebase_messaging: ^14.7.15
  firebase_remote_config: ^4.3.13
  webview_flutter: ^4.7.0
  flutter_no_internet_widget: ^1.0.0+18-dev.1
  google_mobile_ads: ^4.0.0
  device_info_plus: ^9.1.1
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  equatable: ^2.0.5
  syncfusion_flutter_gauges: ^24.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets\images\logo.png
    - assets\images\logo_white.png
    - assets\images\splash_bg.png
    - assets\images\fuel-grey.png
    - assets\images\camera.png
    - assets\images\car_spec_dark.png
    - assets\images\no_image.png
    - assets\images\engine_icon.png
    - assets\images\max_torque.png
    - assets\images\max_power.png
    - assets\images\turning_radius.png
    - assets\images\fuel_tank.png
    - assets\images\wheelbase.png
    - assets\images\bootspace.png
    - assets\images\dimention.png
    - assets\images\tyre.png
    - assets\images\google_icon.png
    - assets\images\phone_icon.png
    - assets\images\manufacurers.png
    - assets\images\adfree.png
    - assets\images\blurred_car_image.png
    - assets\images\Upload-PNG-Image-File.png
    - assets\images\coming_soon.jpg
    - assets\images\offline-300.webp
    - assets\images\google.png
    - assets\images\battery.png
    - assets\images\motor.png
    - assets\images\whatsapp-icon-509x512-c9csi2fs.png
    - assets\images\suspension.png
    - assets\images\battery_cooling.png
    - assets\images\battery_safety.png
    - assets\images\vehicle_type.png

    - assets\animations\Power Motoring.json
    - assets\animations\car_features.json
    - assets\animations\car_loading.json
